name: Build, Test, and Release (if tag)

on:
  push:
    branches: [main]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-?*
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '22'

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npm run check-types

      - name: Lint code
        run: npm run lint

      - name: Build extension
        run: npm run compile

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          path: dist/
          retention-days: 7

  test:
    name: Test Extension
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: dist-build
          path: dist/

      - name: Compile tests
        run: npm run compile-tests

      - name: Run tests
        run: |
          # Install and start virtual display for headless testing
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run -a npm test
        env:
          # Disable VS Code telemetry during tests
          VSCODE_DISABLE_CRASH_REPORTER: true
          # Suppress punycode deprecation warnings from dependencies
          NODE_NO_WARNINGS: 1

  release:
    name: Release to Marketplace
    runs-on: ubuntu-latest
    needs: [test]
    if: startsWith(github.ref_name, 'v')
    permissions:
      id-token: write # For OIDC to Azure for publishing to Marketplace
      contents: write # For creating GitHub Release of new version
      pull-requests: write # For pushing CHANGELOG update back to main
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Azure Login (Workload Identity Federation)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          reverseOrder: true
          excludeTypes: docs, style, refactor, test, ci, dev, deps, chore, revert
          excludeScopes: dev, test, release
          useGitmojis: false

      - name: Publish to VS Code Marketplace
        shell: pwsh
        run: | # powershell
          $Parameters = @(
            # The --azure-credential option relies on DefaultAzureCredential (and we're logged into Azure CLI using OIDC)
            '--azure-credential'
            '--no-git-tag-version'
          )
          if ("${{ github.ref_name }}" -match '-preview') {
            $Parameters += '--pre-release'
          }
          
          # Get version and compare to tag
          # We cannot give vsce the version of tag if it's already in package.json as it will error
          $Version = node -p "require('./package.json').version"
          $TagVersion = '${{ github.ref_name }}' -replace '^v', ''
          if ($TagVersion -ne $Version) {
            $Parameters += $TagVersion
          }
          
          # vsce publish without --no-update-package-json allows us to update the version in package.json and PR it in later step
          vsce publish @Parameters

      - name: Get built VSIX filename
        id: vsix-file
        shell: pwsh
        run: | # powershell
          $vsixFile = Get-ChildItem -Path . -Filter "*.vsix" | Select-Object -First 1
          echo "filename=$($vsixFile.Name)" >> $env:GITHUB_OUTPUT
          Write-Host "Found VSIX file: $($vsixFile.Name)"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.vsix-file.outputs.filename }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-preview') }}
          generate_release_notes: false

      - name: Create Pull Request for Updated Release Files
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          commit-message: |
            chore(release): Release ${{ github.ref_name }}
          title: |
            chore(release): Update files for ${{ github.ref_name }}
          body: Automatic update of files for release ${{ github.ref_name }}.
          labels: release
          base: main
          branch: release-${{ github.ref_name }}
